### ISSUE TITLE
Overrides nightwatch.json globals_path even if not set

### ISSUE THREAD

**Issue by xLegoz** [gextech/grunt-nightwatch#29]
While the globals_path is not set in the nightwatch Gruntfile options, it still overrides any globals_path set by the nightwatch.json and makes the browser.globals object an empy object if not supplied.

Note, it seems to override browser.globals with the nightwatch.json globals variable, and if undefined it overrides it with an empty object - removing the contents of global_path.

**Comment by pateketrueke** [comment]
Hi again, I've published `0.3.2` to npm.

Can you test for that issue again?

**Comment by YoungElPaso** [comment]
I'm pretty sure I still experience this issue.  I'm on 0.5.2. It seems no matter what I put in grunt.initConfig like:
``
nightwatch: {
  options: {
    globals: {'foo':'bar'}
  }
}
``
It all gets stripped out by whatever is in nightwatch.json

**Comment by pateketrueke** [comment]
Interesting, I'll work on that asap.

Thanks for your feedback!

**Comment by YoungElPaso** [comment]
Sorry my bad. I think I just didn't nest the options properly to match what I had in my nightwatch.json file.  I debugged your code pretty well and it works :)

**Comment by pateketrueke** [comment]
Holy moly! :beers:
